ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyUSB0
#ARDUINO_PORT = /dev/ttyAVR*



USER_LIB_PATH = /home/william/Arduino/libraries
BOARD_TAG = nano328
#BOARD_TAG = uno

include /usr/share/arduino/Arduino.mk
