// Generated by gencpp from file underwater_msgs/Baro.msg
// DO NOT EDIT!


#ifndef UNDERWATER_MSGS_MESSAGE_BARO_H
#define UNDERWATER_MSGS_MESSAGE_BARO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace underwater_msgs
{
template <class ContainerAllocator>
struct Baro_
{
  typedef Baro_<ContainerAllocator> Type;

  Baro_()
    : depth(0.0)
    , temp(0.0)  {
    }
  Baro_(const ContainerAllocator& _alloc)
    : depth(0.0)
    , temp(0.0)  {
  (void)_alloc;
    }



   typedef float _depth_type;
  _depth_type depth;

   typedef float _temp_type;
  _temp_type temp;





  typedef boost::shared_ptr< ::underwater_msgs::Baro_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::underwater_msgs::Baro_<ContainerAllocator> const> ConstPtr;

}; // struct Baro_

typedef ::underwater_msgs::Baro_<std::allocator<void> > Baro;

typedef boost::shared_ptr< ::underwater_msgs::Baro > BaroPtr;
typedef boost::shared_ptr< ::underwater_msgs::Baro const> BaroConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::underwater_msgs::Baro_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::underwater_msgs::Baro_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace underwater_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'underwater_msgs': ['/home/cerlab/Underwater/underwater_ws/src/underwater_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::underwater_msgs::Baro_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::underwater_msgs::Baro_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::underwater_msgs::Baro_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::underwater_msgs::Baro_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::underwater_msgs::Baro_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::underwater_msgs::Baro_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::underwater_msgs::Baro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b11505eab6c52277745b4ae83c35f503";
  }

  static const char* value(const ::underwater_msgs::Baro_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb11505eab6c52277ULL;
  static const uint64_t static_value2 = 0x745b4ae83c35f503ULL;
};

template<class ContainerAllocator>
struct DataType< ::underwater_msgs::Baro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "underwater_msgs/Baro";
  }

  static const char* value(const ::underwater_msgs::Baro_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::underwater_msgs::Baro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 depth\n\
float32 temp\n\
";
  }

  static const char* value(const ::underwater_msgs::Baro_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::underwater_msgs::Baro_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.depth);
      stream.next(m.temp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Baro_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::underwater_msgs::Baro_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::underwater_msgs::Baro_<ContainerAllocator>& v)
  {
    s << indent << "depth: ";
    Printer<float>::stream(s, indent + "  ", v.depth);
    s << indent << "temp: ";
    Printer<float>::stream(s, indent + "  ", v.temp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNDERWATER_MSGS_MESSAGE_BARO_H
