// Generated by gencpp from file underwater_robot/Encoder.msg
// DO NOT EDIT!


#ifndef UNDERWATER_ROBOT_MESSAGE_ENCODER_H
#define UNDERWATER_ROBOT_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace underwater_robot
{
template <class ContainerAllocator>
struct Encoder_
{
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
    : encoder_angle(0.0)
    , encoder_speed(0.0)  {
    }
  Encoder_(const ContainerAllocator& _alloc)
    : encoder_angle(0.0)
    , encoder_speed(0.0)  {
  (void)_alloc;
    }



   typedef float _encoder_angle_type;
  _encoder_angle_type encoder_angle;

   typedef float _encoder_speed_type;
  _encoder_speed_type encoder_speed;




  typedef boost::shared_ptr< ::underwater_robot::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::underwater_robot::Encoder_<ContainerAllocator> const> ConstPtr;

}; // struct Encoder_

typedef ::underwater_robot::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::underwater_robot::Encoder > EncoderPtr;
typedef boost::shared_ptr< ::underwater_robot::Encoder const> EncoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::underwater_robot::Encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::underwater_robot::Encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace underwater_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'underwater_robot': ['/home/william/Underwater/underwater_ws/src/underwater_robot/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::underwater_robot::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::underwater_robot::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::underwater_robot::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::underwater_robot::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::underwater_robot::Encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::underwater_robot::Encoder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::underwater_robot::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9991f74e6b5a800497ccb5b53c4ed151";
  }

  static const char* value(const ::underwater_robot::Encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9991f74e6b5a8004ULL;
  static const uint64_t static_value2 = 0x97ccb5b53c4ed151ULL;
};

template<class ContainerAllocator>
struct DataType< ::underwater_robot::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "underwater_robot/Encoder";
  }

  static const char* value(const ::underwater_robot::Encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::underwater_robot::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 encoder_angle\n\
float32 encoder_speed\n\
";
  }

  static const char* value(const ::underwater_robot::Encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::underwater_robot::Encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.encoder_angle);
      stream.next(m.encoder_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::underwater_robot::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::underwater_robot::Encoder_<ContainerAllocator>& v)
  {
    s << indent << "encoder_angle: ";
    Printer<float>::stream(s, indent + "  ", v.encoder_angle);
    s << indent << "encoder_speed: ";
    Printer<float>::stream(s, indent + "  ", v.encoder_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNDERWATER_ROBOT_MESSAGE_ENCODER_H
