// Generated by gencpp from file underwater_robot/Setting.msg
// DO NOT EDIT!


#ifndef UNDERWATER_ROBOT_MESSAGE_SETTING_H
#define UNDERWATER_ROBOT_MESSAGE_SETTING_H

#include <ros/service_traits.h>


#include <underwater_robot/SettingRequest.h>
#include <underwater_robot/SettingResponse.h>


namespace underwater_robot
{

struct Setting
{

typedef SettingRequest Request;
typedef SettingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Setting
} // namespace underwater_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::underwater_robot::Setting > {
  static const char* value()
  {
    return "d545f84ec040b08d5bf2fc0f795d8d0a";
  }

  static const char* value(const ::underwater_robot::Setting&) { return value(); }
};

template<>
struct DataType< ::underwater_robot::Setting > {
  static const char* value()
  {
    return "underwater_robot/Setting";
  }

  static const char* value(const ::underwater_robot::Setting&) { return value(); }
};


// service_traits::MD5Sum< ::underwater_robot::SettingRequest> should match 
// service_traits::MD5Sum< ::underwater_robot::Setting > 
template<>
struct MD5Sum< ::underwater_robot::SettingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::underwater_robot::Setting >::value();
  }
  static const char* value(const ::underwater_robot::SettingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::underwater_robot::SettingRequest> should match 
// service_traits::DataType< ::underwater_robot::Setting > 
template<>
struct DataType< ::underwater_robot::SettingRequest>
{
  static const char* value()
  {
    return DataType< ::underwater_robot::Setting >::value();
  }
  static const char* value(const ::underwater_robot::SettingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::underwater_robot::SettingResponse> should match 
// service_traits::MD5Sum< ::underwater_robot::Setting > 
template<>
struct MD5Sum< ::underwater_robot::SettingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::underwater_robot::Setting >::value();
  }
  static const char* value(const ::underwater_robot::SettingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::underwater_robot::SettingResponse> should match 
// service_traits::DataType< ::underwater_robot::Setting > 
template<>
struct DataType< ::underwater_robot::SettingResponse>
{
  static const char* value()
  {
    return DataType< ::underwater_robot::Setting >::value();
  }
  static const char* value(const ::underwater_robot::SettingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNDERWATER_ROBOT_MESSAGE_SETTING_H
