// Generated by gencpp from file underwater_robot/Setup.msg
// DO NOT EDIT!


#ifndef UNDERWATER_ROBOT_MESSAGE_SETUP_H
#define UNDERWATER_ROBOT_MESSAGE_SETUP_H

#include <ros/service_traits.h>


#include <underwater_robot/SetupRequest.h>
#include <underwater_robot/SetupResponse.h>


namespace underwater_robot
{

struct Setup
{

typedef SetupRequest Request;
typedef SetupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Setup
} // namespace underwater_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::underwater_robot::Setup > {
  static const char* value()
  {
    return "81bdda0e5e12240216c90fa743ee071e";
  }

  static const char* value(const ::underwater_robot::Setup&) { return value(); }
};

template<>
struct DataType< ::underwater_robot::Setup > {
  static const char* value()
  {
    return "underwater_robot/Setup";
  }

  static const char* value(const ::underwater_robot::Setup&) { return value(); }
};


// service_traits::MD5Sum< ::underwater_robot::SetupRequest> should match 
// service_traits::MD5Sum< ::underwater_robot::Setup > 
template<>
struct MD5Sum< ::underwater_robot::SetupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::underwater_robot::Setup >::value();
  }
  static const char* value(const ::underwater_robot::SetupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::underwater_robot::SetupRequest> should match 
// service_traits::DataType< ::underwater_robot::Setup > 
template<>
struct DataType< ::underwater_robot::SetupRequest>
{
  static const char* value()
  {
    return DataType< ::underwater_robot::Setup >::value();
  }
  static const char* value(const ::underwater_robot::SetupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::underwater_robot::SetupResponse> should match 
// service_traits::MD5Sum< ::underwater_robot::Setup > 
template<>
struct MD5Sum< ::underwater_robot::SetupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::underwater_robot::Setup >::value();
  }
  static const char* value(const ::underwater_robot::SetupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::underwater_robot::SetupResponse> should match 
// service_traits::DataType< ::underwater_robot::Setup > 
template<>
struct DataType< ::underwater_robot::SetupResponse>
{
  static const char* value()
  {
    return DataType< ::underwater_robot::Setup >::value();
  }
  static const char* value(const ::underwater_robot::SetupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNDERWATER_ROBOT_MESSAGE_SETUP_H
