// Generated by gencpp from file underwater_robot/SetupRequest.msg
// DO NOT EDIT!


#ifndef UNDERWATER_ROBOT_MESSAGE_SETUPREQUEST_H
#define UNDERWATER_ROBOT_MESSAGE_SETUPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace underwater_robot
{
template <class ContainerAllocator>
struct SetupRequest_
{
  typedef SetupRequest_<ContainerAllocator> Type;

  SetupRequest_()
    : dummy(false)  {
    }
  SetupRequest_(const ContainerAllocator& _alloc)
    : dummy(false)  {
  (void)_alloc;
    }



   typedef uint8_t _dummy_type;
  _dummy_type dummy;




  typedef boost::shared_ptr< ::underwater_robot::SetupRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::underwater_robot::SetupRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetupRequest_

typedef ::underwater_robot::SetupRequest_<std::allocator<void> > SetupRequest;

typedef boost::shared_ptr< ::underwater_robot::SetupRequest > SetupRequestPtr;
typedef boost::shared_ptr< ::underwater_robot::SetupRequest const> SetupRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::underwater_robot::SetupRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::underwater_robot::SetupRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace underwater_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'underwater_robot': ['/home/william/Underwater/underwater_ws/src/underwater_robot/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::underwater_robot::SetupRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::underwater_robot::SetupRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::underwater_robot::SetupRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::underwater_robot::SetupRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::underwater_robot::SetupRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::underwater_robot::SetupRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::underwater_robot::SetupRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef73cd0e20eabb13fd64cbebfb4778d9";
  }

  static const char* value(const ::underwater_robot::SetupRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef73cd0e20eabb13ULL;
  static const uint64_t static_value2 = 0xfd64cbebfb4778d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::underwater_robot::SetupRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "underwater_robot/SetupRequest";
  }

  static const char* value(const ::underwater_robot::SetupRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::underwater_robot::SetupRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool dummy\n\
";
  }

  static const char* value(const ::underwater_robot::SetupRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::underwater_robot::SetupRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dummy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetupRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::underwater_robot::SetupRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::underwater_robot::SetupRequest_<ContainerAllocator>& v)
  {
    s << indent << "dummy: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dummy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNDERWATER_ROBOT_MESSAGE_SETUPREQUEST_H
