ARDUINO_DIR = /usr/share/arduino
#ARDUINO_PORT = /dev/ttyUSB*
#BOARD_TAG = nano328
#ARDUINO_PORT = /dev/ttyUSB2
#ARDUINO_PORT = $(center_motor)
#BOARD_TAG = nano328
BOARD_TAG = uno
ARDUINO_PORT = /dev/ttyACM0



USER_LIB_PATH = /home/william/Arduino/libraries


include /usr/share/arduino/Arduino.mk
