ARDUINO_DIR = /usr/share/arduino

ARDUINO_PORT = ${motor_1}
#ARDUINO_PORT = /dev/ttyUSB2
#ARDUINO_PORT = /dev/ttyAVR*



USER_LIB_PATH = ${arduino_lib_path}
BOARD_TAG = nano328
#BOARD_TAG = uno

include /usr/share/arduino/Arduino.mk
